# aws-auth.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::882540909872:user/eks   #Replace with IAM USER & AWS ACCOUNT
      username: github-deployer
      groups:
        - system:masters
