name: Deploy to EKS with Ingress

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy App to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Change if needed

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-2 --name dev

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Add Helm repo & install NGINX Ingress
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx --create-namespace \
            --set controller.publishService.enabled=true
      - name: Wait for ingress-nginx controller to be ready
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=Ready pods \
            --selector=app.kubernetes.io/component=controller \
            --timeout=180s
      - name: Deploy Application Manifests
        run: |
          kubectl apply -f kubernetes-manifests/deployment.yaml
          kubectl apply -f kubernetes-manifests/service.yaml
          kubectl apply -f kubernetes-manifests/ingress.yaml
